In [1]:
# Importing packages
import numpy as np

In [2]:
sequence_one = 'ATGC'
sequence_two = 'ATGC'

In [3]:
len_seq_one = len(sequence_one)
len_seq_two = len(sequence_two)
print(f"Length of sequence one: {len_seq_one}\nLength of sequence two: {len_seq_two}")

Length of sequence one: 4
Length of sequence two: 4


In [4]:
# Creating empty (zeros) matrix for scores
scores_matrix = np.zeros((len_seq_one+1, len_seq_two+1))
print(scores_matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
# Matrix to check matches and mis-matches
checker_matrix = np.zeros((len_seq_one, len_seq_two))
print(checker_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
# Assigning penalty values
matches = 1
mismatches = -1
gap = -2

In [7]:
for i in range(len_seq_one):
    for j in range(len_seq_two):
        if sequence_one[i] == sequence_two[j]:
            checker_matrix[i][j] = matches
        else:
            checker_matrix[i][j] = mismatches
            
print(checker_matrix)            

[[ 1. -1. -1. -1.]
 [-1.  1. -1. -1.]
 [-1. -1.  1. -1.]
 [-1. -1. -1.  1.]]


In [8]:
# Filling matrix
# Step 01 - Initialisation

for i in range(len_seq_one+1):
    scores_matrix[i][0]=i*gap
for j in range(len_seq_two+1):
    scores_matrix[0][j]=j*gap
    
print(scores_matrix)

[[ 0. -2. -4. -6. -8.]
 [-2.  0.  0.  0.  0.]
 [-4.  0.  0.  0.  0.]
 [-6.  0.  0.  0.  0.]
 [-8.  0.  0.  0.  0.]]


In [9]:
scores_matrix[1][0]

-2.0

In [10]:
for row_i in range(1, len_seq_one+1):
    for col_j in range(1, len_seq_two+1):
        score = max(scores_matrix[row_i][col_j-1]+gap, 
                    scores_matrix[row_i-1][col_j]+gap, 
                    scores_matrix[row_i-1][col_j-1]+checker_matrix[row_i-1][col_j-1])
        scores_matrix[row_i][col_j] = score

In [11]:
scores_matrix

array([[ 0., -2., -4., -6., -8.],
       [-2.,  1., -1., -3., -5.],
       [-4., -1.,  2.,  0., -2.],
       [-6., -3.,  0.,  3.,  1.],
       [-8., -5., -2.,  1.,  4.]])

In [12]:
scores_matrix.shape

(5, 5)

In [15]:
scores_matrix[4][4]

4.0

In [20]:
sequence_one[-1]

'C'

In [21]:
sequence_one

'ATGC'

In [22]:
sequence_two

'ATGC'

In [23]:
sequence_two[-1]

'C'

In [ ]:
if sequence_two[-1] == sequence_one[-1]:
    

In [24]:
max(-1, 0, -4)

0